import {
  Package,
  BadgeDollarSign,
  Users,
  ShieldCheck,
  FileDown,
} from "lucide-react";
import {
  generatePurchaseOrderPDF,
  generateFinancialReportPDF,
  generateFollowUpGeneratorPDF,
  generateComplianceReportPDF,
} from "../utils/pdfGenerator";

function BusinessReports() {
  return (
    <div className="bg-slate-900 rounded-2xl border border-cyan-500/20 p-8">

      <h2 className="text-3xl font-bold text-white">
        📄 Business Reports Center
      </h2>

      <p className="text-slate-400 mt-2">
        Generate official business reports created by AI Agents.
      </p>

      <div className="mt-8 space-y-5">

        {/* Inventory */}

        <div className="flex justify-between items-center bg-slate-800 rounded-xl p-5">

          <div className="flex items-center gap-4">

            <Package
              size={34}
              className="text-cyan-400"
            />

            <div>

              <h3 className="text-white font-semibold text-lg">
                Inventory Purchase Order
              </h3>

              <p className="text-slate-400 text-sm">
                Generated by Inventory Agent
              </p>

            </div>

          </div>

          <button
            onClick={() => alert("Connect Inventory PDF")}
            className="bg-cyan-500 hover:bg-cyan-400 px-5 py-3 rounded-xl font-semibold text-black flex gap-2 items-center"
          >
            <FileDown size={18} />
            Generate PDF
          </button>
<button

onClick={generatePurchaseOrderPDF}

>

Generate PDF

</button>
        </div>

        {/* Finance */}

        <div className="flex justify-between items-center bg-slate-800 rounded-xl p-5">

          <div className="flex items-center gap-4">

            <BadgeDollarSign
              size={34}
              className="text-green-400"
            />

            <div>

              <h3 className="text-white font-semibold text-lg">
                Financial Report
              </h3>

              <p className="text-slate-400 text-sm">
                Generated by Finance Agent
              </p>

            </div>

          </div>

          <button
            onClick={() => alert("Connect Finance PDF")}
            className="bg-green-500 hover:bg-green-400 px-5 py-3 rounded-xl font-semibold text-black flex gap-2 items-center"
          >
            <FileDown size={18} />
            Generate PDF
          </button>

        </div>

        {/* CRM */}

        <div className="flex justify-between items-center bg-slate-800 rounded-xl p-5">

          <div className="flex items-center gap-4">

            <Users
              size={34}
              className="text-purple-400"
            />

            <div>

              <h3 className="text-white font-semibold text-lg">
                CRM Follow-up Report
              </h3>

              <p className="text-slate-400 text-sm">
                Generated by CRM Agent
              </p>

            </div>

          </div>

          <button
            onClick={() => alert("Connect CRM PDF")}
            className="bg-purple-500 hover:bg-purple-400 px-5 py-3 rounded-xl font-semibold text-white flex gap-2 items-center"
          >
            <FileDown size={18} />
            Generate PDF
          </button>

        </div>

        {/* Compliance */}

        <div className="flex justify-between items-center bg-slate-800 rounded-xl p-5">

          <div className="flex items-center gap-4">

            <ShieldCheck
              size={34}
              className="text-orange-400"
            />

            <div>

              <h3 className="text-white font-semibold text-lg">
                Compliance Report
              </h3>

              <p className="text-slate-400 text-sm">
                Generated by Compliance Agent
              </p>

            </div>

          </div>

          <button
            onClick={generateComplianceReportPDF}
            className="bg-orange-500 hover:bg-orange-400 px-5 py-3 rounded-xl font-semibold text-black flex gap-2 items-center"
          >
            <FileDown size={18} />           
             Generate PDF
          </button>

        </div>

      </div>

    </div>
  );
}

export default BusinessReports;