import { Download } from "lucide-react";
import { useState } from "react";
import { generateComplianceReportPDF } from "../utils/pdfGenerator";

function ComplianceReport({ compliance }) {

  const [loading, setLoading] = useState(false);

  const generateReport = () => {

    setLoading(true);

    setTimeout(() => {

      generateComplianceReportPDF(compliance);

      setLoading(false);

    }, 1200);

  };

  return (

    <div className="mt-8 bg-slate-900 rounded-2xl border border-cyan-500/20 overflow-hidden">

      <div className="p-6">

        <h2 className="text-3xl font-bold text-white">
          Compliance Report
        </h2>

        <p className="text-slate-400 mt-2">
          Live compliance summary generated by Compliance Agent
        </p>

      </div>

      <table className="w-full">

        <thead className="bg-slate-800 text-cyan-300">

          <tr>

            <th className="text-left p-5">
              Metric
            </th>

            <th className="text-right pr-8">
              Value
            </th>

          </tr>

        </thead>

        <tbody>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Compliance Rate
            </td>

            <td className="text-right pr-8 text-green-400 font-semibold">
              {compliance.complianceRate}%
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              GST Status
            </td>

            <td className="text-right pr-8 text-cyan-400 font-semibold">
              {compliance.gstStatus}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Licenses
            </td>

            <td className="text-right pr-8 text-purple-400 font-semibold">
              {compliance.licenses}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Expiring Soon
            </td>

            <td className="text-right pr-8 text-yellow-400 font-semibold">
              {compliance.expiringSoon}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Pending Documents
            </td>

            <td className="text-right pr-8 text-orange-400 font-semibold">
              {compliance.pendingDocuments}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Risk Level
            </td>

            <td className="text-right pr-8 text-red-400 font-semibold">
              {compliance.riskScore}
            </td>

          </tr>

        </tbody>

      </table>

      <div className="flex justify-end p-6">

        <button

          onClick={generateReport}

          disabled={loading}

          className="bg-cyan-500 hover:bg-cyan-400 disabled:bg-cyan-700 transition-all duration-300 px-8 py-4 rounded-xl font-bold text-black flex items-center gap-3"

        >

          <Download size={22} />

          {

            loading

              ? "Generating AI Compliance Report..."

              : "Generate Compliance Report"

          }

        </button>

      </div>

    </div>

  );

}

export default ComplianceReport;