import { Download } from "lucide-react";
import { useState } from "react";
import { generateFinancialReportPDF } from "../utils/pdfGenerator";

function FinancialReport({ finance }) {

  const [loading, setLoading] = useState(false);

  const generateReport = () => {

    setLoading(true);

    setTimeout(() => {

      generateFinancialReportPDF(finance);

      setLoading(false);

    }, 1200);

  };

  return (

    <div className="mt-8 bg-slate-900 rounded-2xl border border-cyan-500/20 overflow-hidden">

      <div className="p-6">

        <h2 className="text-3xl font-bold text-white">
          Financial Report
        </h2>

        <p className="text-slate-400 mt-2">
          Live financial summary generated by Finance Agent
        </p>

      </div>

      <table className="w-full">

        <thead className="bg-slate-800 text-cyan-300">

          <tr>

            <th className="text-left p-5">
              Metric
            </th>

            <th className="text-right pr-8">
              Value
            </th>

          </tr>

        </thead>

        <tbody>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Revenue
            </td>

            <td className="text-right pr-8 text-cyan-400 font-semibold">
              ₹{finance.revenue.toLocaleString()}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Expenses
            </td>

            <td className="text-right pr-8 text-red-400 font-semibold">
              ₹{finance.expenses.toLocaleString()}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Profit
            </td>

            <td className="text-right pr-8 text-green-400 font-semibold">
              ₹{finance.profit.toLocaleString()}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Cash Balance
            </td>

            <td className="text-right pr-8 text-yellow-400 font-semibold">
              ₹{finance.cash.toLocaleString()}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Pending Payments
            </td>

            <td className="text-right pr-8 text-orange-400 font-semibold">
              ₹{finance.pendingPayments.toLocaleString()}
            </td>

          </tr>

          <tr className="border-t border-slate-700 hover:bg-slate-800/40">

            <td className="p-5 text-white">
              Monthly Growth
            </td>

            <td className="text-right pr-8 text-green-400 font-semibold">
              +{finance.monthlyGrowth}%
            </td>

          </tr>

        </tbody>

      </table>

      <div className="flex justify-end p-6">

        <button

          onClick={generateReport}

          disabled={loading}

          className="bg-cyan-500 hover:bg-cyan-400 disabled:bg-cyan-700 transition-all duration-300 px-8 py-4 rounded-xl font-bold text-black flex items-center gap-3"

        >

          <Download size={22} />

          {

            loading

              ? "Generating AI Financial Report..."

              : "Generate Financial Report"

          }

        </button>

      </div>

    </div>

  );

}

export default FinancialReport;