import jsPDF from "jspdf";
export function generateFollowUpGeneratorPDF(crm) {
    const customer = crm.customerList[0];

    const reportId = `CRM-${new Date().getFullYear()}-${String(
        Math.floor(Math.random() * 1000) + 1
    ).padStart(4, "0")}`;

    const doc = new jsPDF();

    // =========================
    // HEADER
    // =========================

    doc.setFillColor(6,30,70);
    doc.rect(0,0,210,35,"F");

    doc.setTextColor(255,255,255);
    doc.setFontSize(23);
    doc.text("MSME GROWTH OS",20,16);

    doc.setFontSize(13);
    doc.setTextColor(210,230,255);
    doc.text("AI CRM Follow-up Report",20,26);

    doc.setFontSize(10);
    doc.text(`Report ID : ${reportId}`,145,16);

    // =========================
    // CUSTOMER INFO
    // =========================

    doc.setTextColor(0);

    doc.setFontSize(17);

    doc.text("Customer Information",20,52);

    doc.setDrawColor(180);

    doc.line(20,56,190,56);

    doc.setFontSize(12);

    doc.text(`Customer : ${customer.name}`,20,68);

    doc.text(`Company : ${customer.company}`,20,80);

    doc.text(`Customer Value : ${customer.value}`,20,92);

    doc.text(`Last Purchase : ${customer.lastPurchase}`,20,104);

    doc.text(`Status : ${customer.status}`,20,116);

    // =========================
    // FOOTER
    // =========================

    doc.setDrawColor(180);

    doc.line(20,230,190,230);

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        `Generated : ${new Date().toLocaleString("en-IN")}`,
        20,
        238
    );

    doc.text(
        "Generated by CRM Agent",
        125,
        238
    );

    doc.save("CRM_Follow_Up_Report.pdf");

}export function generatePurchaseOrderPDF() {

    const doc = new jsPDF();

    // ================= HEADER =================

    doc.setFillColor(6,30,70);
    doc.rect(0,0,210,35,"F");

    doc.setTextColor(255,255,255);
    doc.setFontSize(24);
    doc.text("MSME GROWTH OS",20,16);

    doc.setFontSize(13);
    doc.setTextColor(220,235,255);
    doc.text("AI Purchase Order",20,26);

    // Purchase Order ID

    const reportId=`PO-${new Date().getFullYear()}-${String(
    Math.floor(Math.random()*9000)+1000
    )}`;

    doc.setFontSize(10);

    doc.text(
    `PO ID : ${reportId}`,
    145,
    16
    );

    // ================= SUPPLIER =================

    doc.setFontSize(16);
    doc.setTextColor(0);

    doc.text("Supplier Information",20,52);

    doc.line(20,56,190,56);

    doc.setFontSize(12);

    doc.text("Supplier : Metro Textile",20,70);

    doc.text("Product : Black Oversized T-Shirt",20,82);

    doc.text("Quantity : 120 Units",20,94);

    doc.text("Expected Delivery : 30 Jun 2026",20,106);

    doc.text("Estimated Cost : ₹48,000",20,118);

    // ================= FOOTER =================

    doc.setDrawColor(180);

    doc.line(
        20,
        145,
        190,
        145
    );

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        `Generated : ${new Date().toLocaleString("en-IN")}`,
        20,
        153
    );

    doc.text(
        "Generated by MSME Growth OS",
        118,
        153
    );

    doc.save("AI_Purchase_Order.pdf");

}

export function generateFinancialReportPDF() {

    const finance = {
        revenue: 850000,
        expenses: 420000,
        profit: 430000,
        cash: 315000,
        pendingPayments: 68000,
        monthlyGrowth: 18,
    };

    const doc = new jsPDF();

    // baaki saara PDF code...

    // ==========================
    // HEADER
    // ==========================

    doc.setFillColor(6,30,70);
    doc.rect(0,0,210,35,"F");

    doc.setFontSize(24);
    doc.setTextColor(255,255,255);
    doc.text("MSME GROWTH OS",20,16);

    doc.setFontSize(13);
    doc.setTextColor(210,230,255);
    doc.text("AI Financial Report",20,26);

    const reportId=`FIN-${new Date().getFullYear()}-${String(
        Math.floor(Math.random()*1000)+1
    ).padStart(4,"0")}`;

    doc.setFontSize(10);

    doc.text(
        `Report ID : ${reportId}`,
        145,
        16
    );

    // ==========================
    // KPI BOXES
    // ==========================

    doc.setFillColor(0,188,212);
    doc.roundedRect(20,48,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.setTextColor(255);
    doc.text("Revenue",24,57);

    doc.setFontSize(13);
    doc.text(`₹${finance.revenue.toLocaleString()}`,24,65);

    // Expenses

    doc.setFillColor(239,68,68);
    doc.roundedRect(110,48,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("Expenses",114,57);

    doc.setFontSize(13);
    doc.text(`₹${finance.expenses.toLocaleString()}`,114,65);

    // Profit

    doc.setFillColor(34,197,94);
    doc.roundedRect(20,78,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("Profit",24,87);

    doc.setFontSize(13);
    doc.text(`₹${finance.profit.toLocaleString()}`,24,95);

    // Cash

    doc.setFillColor(245,158,11);
    doc.roundedRect(110,78,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("Cash Balance",114,87);

    doc.setFontSize(13);
    doc.text(`₹${finance.cash.toLocaleString()}`,114,95);

    // ==========================
    // SUMMARY
    // ==========================

    doc.setTextColor(0);

    doc.setFontSize(16);

    doc.text("Financial Summary",20,118);

    doc.setDrawColor(180);

    doc.line(20,122,190,122);

    doc.setFontSize(12);

    doc.text(
        `Pending Payments : ₹${finance.pendingPayments.toLocaleString()}`,
        20,
        140
    );

    doc.text(
        `Monthly Growth : ${finance.monthlyGrowth}%`,
        20,
        154
    );

    doc.text(
        "Cash Flow Status : Healthy",
        20,
        168
    );

    // ==========================
    // FOOTER
    // ==========================

    doc.setDrawColor(180);

    doc.line(
        20,
        270,
        190,
        270
    );

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        `Generated : ${new Date().toLocaleString("en-IN")}`,
        20,
        278
    );

    doc.text(
        "Generated by MSME Growth OS",
        120,
        278
    );

    doc.save("AI_Financial_Report.pdf");

}

export function generateComplianceReportPDF(compliance = {
  complianceRate: 98,
  gstStatus: "Filed",
  licenses: 5,
  expiringSoon: 2,
  pendingDocuments: 4,
  riskScore: "Low",
}) {
    const doc = new jsPDF();

    // ==========================
    // HEADER
    // ==========================

    doc.setFillColor(6,30,70);
    doc.rect(0,0,210,35,"F");

    doc.setFontSize(24);
    doc.setTextColor(255,255,255);
    doc.text("MSME GROWTH OS",20,16);

    doc.setFontSize(13);
    doc.setTextColor(210,230,255);
    doc.text("AI Compliance Report",20,26);

    const reportId=`COM-${new Date().getFullYear()}-${String(
        Math.floor(Math.random()*1000)+1
    ).padStart(4,"0")}`;

    doc.setFontSize(10);

    doc.text(
        `Report ID : ${reportId}`,
        145,
        16
    );

    // ==========================
    // KPI BOXES
    // ==========================

    // Compliance Rate

    doc.setFillColor(34,197,94);
    doc.roundedRect(20,48,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.setTextColor(255);
    doc.text("Compliance",24,57);

    doc.setFontSize(13);
    doc.text(`${compliance.complianceRate}%`,24,65);

    // GST Status

    doc.setFillColor(0,188,212);
    doc.roundedRect(110,48,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("GST Status",114,57);

    doc.setFontSize(13);
    doc.text(`${compliance.gstStatus}`,114,65);

    // Licenses

    doc.setFillColor(139,92,246);
    doc.roundedRect(20,78,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("Licenses",24,87);

    doc.setFontSize(13);
    doc.text(`${compliance.licenses}`,24,95);

    // Expiring

    doc.setFillColor(245,158,11);
    doc.roundedRect(110,78,75,22,3,3,"F");

    doc.setFontSize(11);
    doc.text("Expiring",114,87);

    doc.setFontSize(13);
    doc.text(`${compliance.expiringSoon}`,114,95);

    // ==========================
    // SUMMARY
    // ==========================

    doc.setFontSize(16);
    doc.setTextColor(0);

    doc.text("Compliance Summary",20,118);

    doc.setDrawColor(180);
    doc.line(20,122,190,122);

    doc.setFontSize(12);

    doc.text(
        `Pending Documents : ${compliance.pendingDocuments}`,
        20,
        140
    );

    doc.text(
        `Risk Level : ${compliance.riskScore}`,
        20,
        154
    );

    doc.text(
        `GST Status : ${compliance.gstStatus}`,
        20,
        168
    );

    // ==========================
    // FOOTER
    // ==========================

    doc.setDrawColor(180);
    doc.line(20,270,190,270);

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        `Generated : ${new Date().toLocaleString("en-IN")}`,
        20,
        278
    );

    doc.text(
        "Generated by MSME Growth OS",
        118,
        278
    );

    doc.save("AI_Compliance_Report.pdf");

}
    